/**
 * THIS FILE IS AUTO-GENERATED FROM src/main/ipc/schemas.ts
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run 'npm run build:schemas' to regenerate
 */

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuditLogEntrySchema = exports.ActivePromptsSchema = exports.WorkspaceSelectionUpdateSchema = exports.WorkspaceSelectionSchema = exports.InstructionCreateSchema = exports.InstructionSchema = exports.PromptSchema = exports.PreferenceSetSchema = exports.PreferenceGetSchema = exports.OpenDocsSchema = exports.FolderSelectionSchema = exports.CancelFileLoadingSchema = exports.FileListRequestSchema = exports.FileSaveSchema = exports.FileContentResponseSchema = exports.RequestFileContentSchema = exports.FileContentRequestSchema = exports.WorkspaceRenameSchema = exports.WorkspaceDeleteSchema = exports.WorkspaceTouchSchema = exports.WorkspaceLoadSchema = exports.WorkspaceUpdateSchema = exports.WorkspaceCreateSchema = exports.WorkspaceSchema = void 0;
const zod_1 = require("zod");
// Workspace schemas
exports.WorkspaceSchema = zod_1.z.object({
    // Some environments use UUID ids; others use human-readable names as ids.
    // Relax to string() to support both until full migration completes.
    id: zod_1.z.string(),
    name: zod_1.z.string().min(1).max(255),
    folderPath: zod_1.z.string(),
    state: zod_1.z.record(zod_1.z.string(), zod_1.z.unknown()),
    createdAt: zod_1.z.number(),
    updatedAt: zod_1.z.number(),
    lastAccessed: zod_1.z.number()
});
exports.WorkspaceCreateSchema = zod_1.z.object({
    name: zod_1.z.string().min(1).max(255),
    folderPath: zod_1.z.string(),
    state: zod_1.z.record(zod_1.z.string(), zod_1.z.unknown()).optional()
});
exports.WorkspaceUpdateSchema = zod_1.z.object({
    // Allow both UUID and numeric string IDs (database uses INTEGER PRIMARY KEY)
    id: zod_1.z.string().min(1),
    state: zod_1.z.record(zod_1.z.string(), zod_1.z.unknown())
});
exports.WorkspaceLoadSchema = zod_1.z.object({
    id: zod_1.z.string().min(1)
});
exports.WorkspaceTouchSchema = zod_1.z.object({
    id: zod_1.z.string().min(1)
});
exports.WorkspaceDeleteSchema = zod_1.z.object({
    // Allow both UUID and numeric string IDs (database uses INTEGER PRIMARY KEY)
    id: zod_1.z.string().min(1)
});
exports.WorkspaceRenameSchema = zod_1.z.object({
    // Allow both UUID and numeric string IDs (database uses INTEGER PRIMARY KEY)
    id: zod_1.z.string().min(1),
    newName: zod_1.z.string().min(1).max(255)
});
// File schemas
exports.FileContentRequestSchema = zod_1.z.object({
    // Allow both UUID and numeric string IDs (database uses INTEGER PRIMARY KEY)
    workspaceId: zod_1.z.string().min(1),
    filePath: zod_1.z.string(),
    lineRanges: zod_1.z.array(zod_1.z.object({
        start: zod_1.z.number().int().positive(),
        end: zod_1.z.number().int().positive()
    })).optional()
});
// Legacy file content request schema for backward compatibility
exports.RequestFileContentSchema = zod_1.z.object({
    filePath: zod_1.z.string()
});
exports.FileContentResponseSchema = zod_1.z.object({
    content: zod_1.z.string(),
    tokenCount: zod_1.z.number().int(),
    hash: zod_1.z.string(),
    compressed: zod_1.z.boolean()
});
exports.FileSaveSchema = zod_1.z.object({
    // Allow both UUID and numeric string IDs (database uses INTEGER PRIMARY KEY)
    workspaceId: zod_1.z.string().min(1),
    filePath: zod_1.z.string(),
    content: zod_1.z.string(),
    tokenCount: zod_1.z.number().int().optional()
});
exports.FileListRequestSchema = zod_1.z.object({
    folderPath: zod_1.z.string(),
    exclusionPatterns: zod_1.z.array(zod_1.z.string()).optional(),
    requestId: zod_1.z.string().nullable().optional()
});
exports.CancelFileLoadingSchema = zod_1.z.object({
    requestId: zod_1.z.string()
});
// Folder selection schema
exports.FolderSelectionSchema = zod_1.z.object({});
// Docs schema
exports.OpenDocsSchema = zod_1.z.object({
    docName: zod_1.z.string().optional()
});
// Preference schemas
exports.PreferenceGetSchema = zod_1.z.object({
    key: zod_1.z.string()
});
exports.PreferenceSetSchema = zod_1.z.object({
    key: zod_1.z.string(),
    value: zod_1.z.unknown(),
    encrypted: zod_1.z.boolean().optional().default(false)
});
// Prompt schemas
exports.PromptSchema = zod_1.z.object({
    id: zod_1.z.string(),
    type: zod_1.z.enum(['system', 'role']),
    name: zod_1.z.string(),
    content: zod_1.z.string(),
    tokenCount: zod_1.z.number().int().optional(),
    isActive: zod_1.z.boolean(),
    createdAt: zod_1.z.number().optional(),
    updatedAt: zod_1.z.number().optional()
});
// Instruction schemas
exports.InstructionSchema = zod_1.z.object({
    id: zod_1.z.string(),
    name: zod_1.z.string().min(1).max(255),
    content: zod_1.z.string(),
    category: zod_1.z.string().optional(),
    createdAt: zod_1.z.number(),
    updatedAt: zod_1.z.number()
});
exports.InstructionCreateSchema = zod_1.z.object({
    name: zod_1.z.string().min(1).max(255),
    content: zod_1.z.string(),
    category: zod_1.z.string().optional()
});
// Workspace selection schemas
exports.WorkspaceSelectionSchema = zod_1.z.object({
    selectedFiles: zod_1.z.array(zod_1.z.object({
        path: zod_1.z.string(),
        lines: zod_1.z.array(zod_1.z.object({
            start: zod_1.z.number().int().positive(),
            end: zod_1.z.number().int().positive()
        })).optional(),
        content: zod_1.z.string().optional(),
        tokenCount: zod_1.z.number().int().optional(),
        isFullFile: zod_1.z.boolean().optional(),
        isContentLoaded: zod_1.z.boolean().optional()
    })),
    lastModified: zod_1.z.number()
});
exports.WorkspaceSelectionUpdateSchema = zod_1.z.object({
    selectedFiles: zod_1.z.array(zod_1.z.object({
        path: zod_1.z.string(),
        lines: zod_1.z.array(zod_1.z.object({
            start: zod_1.z.number().int().positive(),
            end: zod_1.z.number().int().positive()
        })).optional(),
        content: zod_1.z.string().optional(),
        tokenCount: zod_1.z.number().int().optional(),
        isFullFile: zod_1.z.boolean().optional(),
        isContentLoaded: zod_1.z.boolean().optional()
    })),
    lastModified: zod_1.z.number()
});
// Active prompts schemas
exports.ActivePromptsSchema = zod_1.z.object({
    systemPromptIds: zod_1.z.array(zod_1.z.string()),
    rolePromptIds: zod_1.z.array(zod_1.z.string())
});
// Audit log schemas
exports.AuditLogEntrySchema = zod_1.z.object({
    id: zod_1.z.number(),
    operation: zod_1.z.string(),
    tableName: zod_1.z.string().optional(),
    recordId: zod_1.z.string().optional(),
    oldValue: zod_1.z.string().optional(),
    newValue: zod_1.z.string().optional(),
    timestamp: zod_1.z.number()
});
