#!/usr/bin/env node

/**
 * Build script to generate CJS version of IPC schemas from TypeScript source.
 * This ensures a single source of truth for IPC validation schemas.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Paths
const srcPath = path.join(__dirname, '..', 'src', 'main', 'ipc', 'schemas.ts');
const libDir = path.join(__dirname, '..', 'lib', 'main', 'ipc');
const outputPath = path.join(libDir, 'schemas.cjs');

console.log('Building IPC schemas...');

try {
  // Ensure lib directory exists
  fs.mkdirSync(libDir, { recursive: true });
  
  // Use TypeScript compiler to transpile the schemas
  // We need to compile it to CommonJS format for the main process
  const tempDir = path.join(__dirname, '..', '.temp-schemas');
  fs.mkdirSync(tempDir, { recursive: true });
  
  // Create a temporary tsconfig for building just the schemas
  const tempTsConfig = {
    compilerOptions: {
      target: 'ES2020',
      module: 'commonjs',
      lib: ['ES2020'],
      outDir: tempDir,
      rootDir: path.join(__dirname, '..'),
      declaration: false,
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      moduleResolution: 'node'
    },
    files: [srcPath]
  };
  
  const tempTsConfigPath = path.join(tempDir, 'tsconfig.schemas.json');
  fs.writeFileSync(tempTsConfigPath, JSON.stringify(tempTsConfig, null, 2));
  
  // Compile the TypeScript file
  console.log('Compiling schemas.ts to CommonJS...');
  try {
    execSync(`npx tsc --project ${tempTsConfigPath}`, { stdio: 'inherit' });
  } catch (error) {
    console.error('TypeScript compilation failed:', error.message);
    // Clean up and exit
    fs.rmSync(tempDir, { recursive: true, force: true });
    process.exit(1);
  }
  
  // Read the compiled output - it will preserve the folder structure
  const compiledPath = path.join(tempDir, 'src', 'main', 'ipc', 'schemas.js');
  let compiledContent = fs.readFileSync(compiledPath, 'utf-8');
  
  // Add a header comment
  const header = `/**
 * THIS FILE IS AUTO-GENERATED FROM src/main/ipc/schemas.ts
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run 'npm run build:schemas' to regenerate
 */

`;
  
  compiledContent = header + compiledContent;
  
  // Write to the output location
  fs.writeFileSync(outputPath, compiledContent);
  
  // Clean up temporary directory
  fs.rmSync(tempDir, { recursive: true, force: true });
  
  console.log(`✅ IPC schemas built successfully: ${outputPath}`);
  
  // Verify the output is valid JavaScript
  try {
    require(outputPath);
    console.log('✅ Output validation passed');
  } catch (error) {
    console.error('❌ Output validation failed:', error.message);
    process.exit(1);
  }
  
} catch (error) {
  console.error('❌ Error building schemas:', error.message);
  process.exit(1);
}